#!/usr/bin/env bash

docker build -t test-workspace .
docker run --rm -ti \
    -v $(pwd):/var/www/app \
    -v $HOME/.ssh:/home/daker/.ssh:ro \
    -v $HOME/.docker-workspace:/home/daker/.docker-workspace \
    --env PGID=$(id -g) --env PUID=$(id -u) \
    test-workspace $@
