version: "2"
services:
  app-native-osx:
    image: travissouth/workspace:${PUID}
    build:
      context: ./
      args:
      - PUID=${PUID}
      - PGID=${PGID}
    ports: 
      - "0.0.0.0:${PORTS}:8001"
    entrypoint: ["/sbin/my_init", "--"]
    command: []
    volumes:
      - ${HOME}/.ssh:/home/daker/.ssh
      - ${HOME}/.docker-workspace:/home/daker/.docker-workspace
      - ${HOME}/.bash_profile:/home/daker/.bash_profile
      - ${HOME}/.gitconfig:/home/daker/.gitconfig
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /home/daker/${FOLDER_NAME}

