version: "2"
services:
  app-native-osx:
    image: travissouth/workspace:${PUID}
    build:
      context: ./
      args:
      - PUID=${PUID}
      - PGID=${PGID}
    ports: 
      - "0.0.0.0:${PORTS}:${CONTAINER_PORTS}"
    entrypoint: ["/sbin/my_init", "--"]
    command: []
    volumes:
      - ${HOME}/.ssh:/home/daker/.ssh:delegated
      - ${HOME}/.oh-my-zsh:/home/daker/.oh-my-zsh:delegated
      - ${HOME}/.zshrc:/home/daker/.zshrc:delegated
      - ${HOME}/.gitconfig:/home/daker/.gitconfig:delegated
      - /var/run/docker.sock:/var/run/docker.sock:delegated
      - ${HOME}/.docker-workspace:/home/daker/.docker-workspace:delegated
    working_dir: /home/daker/${FOLDER_NAME}
