version: "2"
services:
  app-native-osx:
    image: travissouth/workspace:${PUID}
    build:
      context: ./
      args:
      - PUID=${PUID}
      - PGID=${PGID}
    ports: 
      - "0.0.0.0:${PORTS}:${CONTAINER_PORTS}"
    entrypoint: ["/sbin/my_init", "--"]
    command: []
    volumes:
      - ${HOME}/.ssh:/home/daker/.ssh:delegated
      - ${HOME}/.bash_profile:/home/daker/.bash_profile:delegated
      - ${HOME}/.gitconfig:/home/daker/.gitconfig:delegated
      - /var/run/docker.sock:/var/run/docker.sock:delegated
    working_dir: /home/daker/${FOLDER_NAME}
