#!/usr/bin/env bash

set -e

command -v git >/dev/null 2>&1 || { echo >&2 "I require git.  Aborting."; exit 1; }
command -v docker >/dev/null 2>&1 || { echo >&2 "I require docker.  Aborting."; exit 1; }

if [ -d ~/.docker-workspace ]; then
    chown -R $(id -u):$(id -g) ~/.docker-workspace
fi
mkdir -p ~/.docker-workspace/src
cd ~/.docker-workspace/src
rm -rf docker-workspace
git clone https://github.com/travis-south/docker-workspace.git
cd docker-workspace
docker build --force-rm --pull --build-arg PUID=$(id -u) --build-arg PGID=$(id -g) -t travissouth/workspace:$(id -u) .
rm -f ~/ws
cp ./ws ~/ws
chmod +x ~/ws
~/ws
