#!/usr/bin/env bash

set -e

command -v git >/dev/null 2>&1 || { echo >&2 "I require git.  Aborting."; exit 1; }
command -v docker >/dev/null 2>&1 || { echo >&2 "I require docker.  Aborting."; exit 1; }

case "$(uname)" in
  Darwin)
    command -v gem >/dev/null 2>&1 || { echo >&2 "I require gem.  Aborting."; exit 1; }
    sudo gem install docker-sync
    ;;
esac

if [ -d ~/.docker-workspace ]; then
    sudo chown -R $(id -u):$(id -g) ~/.docker-workspace
fi
mkdir -p ~/.docker-workspace/src
cd ~/.docker-workspace/src
rm -rf docker-workspace
git clone https://github.com/travis-south/docker-workspace.git
cd docker-workspace
sudo rm -f /usr/local/bin/ws
sudo cp ./ws /usr/local/bin/ws
sudo chmod a+x /usr/local/bin/ws
ws
