#!/usr/bin/env bash

docker run --rm -ti \
    -v $HOME/.ssh:/home/daker/.ssh \
    -v $HOME/.docker-workspace:/home/daker/.docker-workspace \
    --volume=/var/run/docker.sock:/var/run/docker.sock \
    -v $(pwd):$(pwd) \
    -w $(pwd) \
    --env PGID=$(id -g) --env PUID=$(id -u) \
    test-workspace $@
